### ISSUE TITLE
Setting password via csv doesn't work

### ISSUE THREAD

**Issue by pranapro** [namoscato/snap-cli#2]
I tried to set a password in the input file but was not able to log in w/ that password after the user was created (and verified). During login, Snap just reported that the password entered was incorrect. 

I did specify that a password column was to be used in the cmd:
 snap user:provision .\test3.csv -u 0 -e 1 -p 2 -o output3.csv

**Comment by namoscato** [comment]
@pranapro, I just tested that flow again and could not reproduce the issue you are describing.

What does your CSV look like? Does the command output any errors? Did you click on the verification link in the email sent via Snap! Cloud?

**Comment by pranapro** [comment]
I'm attaching a csvI used to create the users and the resulting output csv
(just created each user and said writing output CSV). There were no errors
from the command output. I knew that the accounts got created b/c
verification link email was sent. I clicked on the link to enable the
account but was still unable to login with the password I had specified in
the initial input file.

I'm able to reset the password for the auto created account but I'm
thinking there must be something quirky with the initial csv?? One least
thing, the command I used in a powershell window to run was: snap
user:provision .\test3.csv -u 0 -e 1 -p 2 -o output3.csv

Thanks for looking in to this. It seems like it should just work!

Shikha

**Comment by namoscato** [comment]
@pranapro, sorry the attachments did not come through! Could you try uploading the files again through GitHub or another file share service?

**Comment by pranapro** [comment]
Sorry, github made me change the extension from csv before letting me upload. Ugh, and I just looked and it changed the formatting of the output file but I think the input is still good.

[output3.txt](https://github.com/namoscato/snap-cli/files/2355130/output3.txt)
[test3.txt](https://github.com/namoscato/snap-cli/files/2355131/test3.txt)

**Comment by namoscato** [comment]
@pranapro, no worries!

Ah yeah, the space prefixing the email and password column values in `test3.txt` is causing the issue. Removing the spaces should solve the problem.

I suppose we could _trim_ the value (of whitespace) after parsing – thoughts?

**Comment by pranapro** [comment]
doh! I removed the spaces and everything works grand. Sorry about that and thank you for taking a look. I think using trim would work fine or returning a validation error to the user and making me (ahem, them) fix the input file is also an option. It's unfortunate that snap creates the user - I wonder what the client actually set as the password when there's a space present? I wasn't able to log in to those accounts.

**Comment by namoscato** [comment]
Yeah, I am cool trimming the CSV values to mitigate this in the future. The Snap! web client or API probably trims whitespace on the form inputs, causing the mismatch.

**Comment by namoscato** [comment]
@pranapro, this is fixed in v0.1.2.
